### ISSUE TITLE
Date error messaging

### ISSUE THREAD

**Issue by bennpearson** [ONSdigital/eq-survey-runner#406] opened 2016-09-02 10:34 UTC
### Expected behaviour

1 error message should show when there is a single error
### Actual behaviour

2 error messages showing for a single error
### Steps to reproduce the behaviour
- Launch 1_0215 questionnaire
- For "What are the dates of the sales period you are reporting for?"
- Select the 'From' date: 28th February 2001
- Select the 'To' date: 28 February 2000
- Submit the form
- Amend the 'To' date to: 31 February 2000
- Submit the form
#### Browser

All
#### Operating System

All
### Screenshot

![screen shot 2016-09-02 at 11 27 03](https://cloud.githubusercontent.com/assets/130312/18201234/dab9bd72-7100-11e6-87d6-ad453bc635cc.png)

**Comment by yoganandkunche** [comment] 2016-10-26 15:03
Retested this defect in pre-prod and it works as expected. (only one error displayed)

**Comment by collisdigital** [comment] 2016-10-26 17:28
Closing as cannot reproduce any longer.

**Closed as completed by collisdigital** 2016-10-26 17:28 UTC
Labels: bug, minor (P4)
