### ISSUE TITLE
Submitted answers appear editable in view-submission page

### ISSUE THREAD

**Issue by armstrongb** [ONSdigital/eq-survey-runner#1492] opened 2018-03-13 16:01 UTC
### Expected behaviour
The summary output of submitted data without edit links
### Actual behaviour
- The summary output shows edit links.
- Edit links when clicked take the user to an expired session page.
### Steps to reproduce the behaviour
Complete a survey on pre-prod and view the submission via the link.
#### Browser
Chrome 64
#### Operating System
Apple High Sierra
### Screenshot
![ons-eq-submitted-answers-issue](https://user-images.githubusercontent.com/22910336/37353308-fe84edb6-26d6-11e8-8e63-e1270f096e08.png)

**Comment by nealedj** [comment] 2018-03-13 16:05
Duplicate of #1488

**Closed as completed** 2018-03-14 10:11 UTC
Labels: major (P2)
