### ISSUE TITLE
Navigation issue with validation errors

### ISSUE THREAD

**Issue by LJBabbage** [ONSdigital/eq-survey-runner#336] opened 2016-07-26 10:51 UTC
### Expected behaviour

Navigation works if validation is triggered (back, forward button) 
### Actual behaviour

At the moment if a user triggers a validation error, the back and forward button do not work as expected
### Steps to reproduce the behaviour

Use Stars Wars, generate an error on the second page, correct it and go to summary, then hit back a few times and see what happens

**Comment by warrenbailey** [comment] 2016-07-27 07:45
Since we're about to rework the validation component, I suggest we park this temporarily and fix it as part of that.

**Comment by dhilton** [comment] 2016-08-01 12:07
Reviewing this now to see if it still occurs after the work we've done in this area on master.

**Comment by dhilton** [comment] 2016-08-01 13:15
Still an issue on master at 9ed21f570871e658ac6c2e7d6316e910d265e3e9

**Comment by warrenbailey** [comment] 2016-08-01 14:04
What is happening here is kind of correct. The application issues a redirect after every POST request. Therefore if a page fails validation it issues a redirect back to the same page. The browser then issues another GET request. Every GET request is added to the browsers history.

Each time the user hits the back button they pop the last GET request of the browser history stack and reissue it. Since there's two GET requests for the page with the validation errors, you see it twice before go to the previous page. If you submitted the page multiple times with validation errors, you'd have multiple GET requests in your history for that page.

I suggest we don't think this (not sure how'd we do it anyway) unless the issue is raised during user testing.

**Comment by dhilton** [comment] 2016-08-01 14:05
Closing this as evidenced above.

**Closed as completed by dhilton** 2016-08-01 14:05 UTC
Labels: bug, wontfix, major (P2)
